"""Add size, shape, and color to Detection model

Revision ID: f220aa4874fc
Revises: 4463217389c5
Create Date: 2025-09-06 13:48:51.505700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f220aa4874fc'
down_revision = '4463217389c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('shape', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=True))
        batch_op.drop_column('confidence')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence', sa.FLOAT(), nullable=True))
        batch_op.drop_column('color')
        batch_op.drop_column('shape')
        batch_op.drop_column('size')

    # ### end Alembic commands ###
